### ISSUE TITLE
Tk error

### ISSUE THREAD

**Issue by gingerbeardman** [Nythepegasus/Pegasus-Skin-Editor#1]
I have no idea how to solve this.

```
% python3 Editor.py 
Traceback (most recent call last):
  File "/Users/matt/Downloads/2024-04-18/Pegasus-Skin-Editor-master/Editor.py", line 6, in <module>
    import tkinter as tk
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'
```

**Comment by gingerbeardman** [comment]
this did it
`brew install python-tk`
